= Ninjector

image:https://github.com/patbaumgartner/ninjector/actions/workflows/ci.yml/badge.svg["CI", link="https://github.com/patbaumgartner/ninjector/actions/workflows/ci.yml"]
image:https://img.shields.io/badge/Spring%20Framework-7.0.7-brightgreen.svg["Spring Framework", link="https://spring.io/projects/spring-framework"]
image:https://img.shields.io/badge/JUnit-6.0.3-blue.svg["JUnit", link="https://junit.org/junit5/"]
image:https://img.shields.io/badge/Java-17%2B-orange.svg["Java", link="https://adoptium.net/"]

Ninjector is the cure for a disease called Field Injection Anxiety, widely diagnosed amongst software developers that care about their code.
The disease is caused by injection frameworks all too easily allowing http://www.martinfowler.com/articles/injection.html[dependency injection] into a class' fields which seems to be a convenient thing to do in the first place but will inevitably bite you in the back later on.
For a more detailed analysis of symptoms and consequences, see http://olivergierke.de/2013/11/why-field-injection-is-evil[this blog post]

== What does it do?

```java
@Configuration
@ComponentScan
@DisableFieldInjection
class Application { … }

/**
 * This class will fail the ApplicationContext to bootstrap
 * due to the injection annotation used on a field.
 **/
@Component
class ApplicationComponent {

  @Autowired MyCollaborator collaborator;
}

```

`@DisableFieldInjection` registers a tiny Spring extension that will pre-process the bean instances about to be created, scan their fields for common injection annotations (e.g. `@Inject`, `@Autowired`, `@Resource`) and reject the bean instantiation right away.

== Prerequisites

* JDK 17 or later
* Maven 3.9+ (the project does not ship a wrapper)
* Spring Framework 7.x (managed by the project)
* JUnit Jupiter 6.x (managed by the project)

== Build and Test

[source,bash]
----
mvn verify
----

This compiles the sources, runs the JUnit Jupiter tests and packages the JAR.

== License

Released under the http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].

